### ISSUE TITLE
Replace deprecated Cloudant client library

### ISSUE THREAD

**Issue by emlaver** [ibm-cloud-docs/node#10]
The `nodejs-cloudant` library was deprecated earlier this year.  The references to this library need to be replaced with the latest and supported [cloudant-node-sdk](https://github.com/IBM/cloudant-node-sdk) library (`@ibm-cloud/cloudant` package).  Also all examples need to be updated.

**Comment by michaelbowler** [comment]
@emlaver FYI, the Node programming guide is about to be removed from our IBM Cloud docs collection, therefore I need to close this issue.
