### ISSUE TITLE
Failing to compile

### ISSUE THREAD

**Issue by raheelzubairy** [ibm-cloud-docs/node#6]
We installed the `ibm-cloud-env` library for our project using `npm install ibm-cloud-env`.

However, as soon as we import the library using:
`import * as cloudEnv from 'ibm-cloud-env';`
or
`const cloudEnv = require('ibm-cloud-env');`

We are getting the following error:
![Screen Shot 2019-12-12 at 7 43 02 PM](https://user-images.githubusercontent.com/27243319/70763056-63435880-1d18-11ea-9cfb-e16218c17256.png)

We would appreciate help urgently as building this project for client

**Comment by christoc-ibm** [comment]
@raheelzubairy 

This issue just now came to me. Is this still a problem? If so, please reach out to the dev team here:
https://slack-invite-ibm-cloud-tech.mybluemix.net/

Thank you.
