### ISSUE TITLE
Please fix link - It does not work.

### ISSUE THREAD

**Issue by kiranshashiny** [ibm-cloud-docs/node#7]
At the end of the document the link "check out the docs" does not work.
Link 🥇 
https://cloud.ibm.com/docs/node?topic=nodejs-cloudant#test-cloudant
=== Cut and Paste of the line that has the link does not work ==

To learn more about and take advantage of all of the features that IBM Cloudant offers, "check out the docs".

**Comment by christx83** [comment]
This link is now fixed. Thank you for reporting it.
